"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import { AgentIcon } from "@/components/AgentIcon";
import { DEMO_EVENTS } from "@/components/DemoControls";
import { getAgentPlatformLabel, liveFeed, stats, type FeedItem } from "@/lib/mockData";
import {
  simulateAgentAction,
  buildSimulatedReasoningWhat,
  buildSimulatedReasoningWhy,
  buildSimulatedRiskProfile,
} from "@/lib/simulateAgent";
import { pendingStore } from "@/lib/stores";
import { useLocale, useT } from "@/lib/i18n/LocaleProvider";
import { useDesktopNotifications } from "@/lib/useDesktopNotifications";
import { toast } from "sonner";
import { cn } from "@/lib/utils";

type FilterKind = "all" | "pending" | "auto" | "recent";

const FILTERS: readonly FilterKind[] = ["all", "pending", "auto", "recent"];

/** Maps reason text to a visual tone for the rule pill. Binary: warn when the
 *  rule was triggered as a red flag ("exceeds", "stored-value", etc.) — every
 *  other reason reads as a pass (under cap, allowlisted, etc.). */
function ruleTone(reason: string): "ok" | "warn" {
  if (/超過|高於|新地址|跨鏈|審核|確認|提領|可儲值|警示|重複扣款|exceeds|above|new address|bridge|review|withdrawal|alert|recurring/i.test(reason)) {
    return "warn";
  }
  return "ok";
}

export function AgentFeed({
  limit = 5,
  viewAllHref = "/audit",
}: {
  limit?: number;
  viewAllHref?: string;
} = {}) {
  const t = useT();
  const { locale } = useLocale();
  const { notify } = useDesktopNotifications();
  const [items, setItems] = useState<FeedItem[]>(() => liveFeed.slice(0, limit));
  const [filter, setFilter] = useState<FilterKind>("all");
  const [resolving, setResolving] = useState<Set<string>>(new Set());
  const tickRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const handleResolve = (id: string) => {
    if (resolving.has(id)) return;
    setResolving((prev) => new Set(prev).add(id));
    setTimeout(() => {
      setItems((prev) => prev.filter((i) => i.id !== id));
      setResolving((prev) => {
        const next = new Set(prev);
        next.delete(id);
        return next;
      });
      // Drop the oldest pending approval from the queue too — keeps the
      // dashboard hero count in lockstep with the visual row resolve.
      const queue = pendingStore.getAll();
      if (queue.length > 0) pendingStore.remove(queue[0].id);
    }, 600);
  };

  useEffect(() => {
    const tick = () => {
      const next = simulateAgentAction();
      setItems((prev) => [next, ...prev].slice(0, limit));
      if (next.status === "pending") {
        // Synthesize a matching PendingApproval so the queue grows with the
        // simulator. The reasoning + riskProfile builders live in
        // simulateAgent.ts so the rendered detail view reads naturally
        // (proper agent display name, agent-aware action verbs, full
        // 6-field risk profile incl. Risk Level) instead of bottoming out
        // on the generic "X wants to pay Y for Z" fallback template.
        const reasoningWhat = buildSimulatedReasoningWhat(
          next.agent,
          next.amount,
          next.merchant,
        );
        const reasoningWhy = buildSimulatedReasoningWhy(next.agent);
        const fallbackApprovalReason = {
          zh: "超出規則邊界，需要人工核准",
          en: "Outside the rule boundary; manual approval required",
        };
        pendingStore.add({
          id: `synth_${next.id}`,
          agent: next.agent,
          merchant: next.merchant,
          amount: next.amount,
          currency: "USDC",
          timestamp: new Date().toISOString().replace("T", " ").slice(0, 16),
          why: reasoningWhy,
          context: {
            taskId: { zh: "活動模擬產生", en: "Generated by activity sim" },
            spentOnTask: 0,
            remainingBudget: 0,
            merchantTrust: "first-time",
            similarPastTransactions: 0,
          },
          triggeredRule: next.reason,
          severity: "warning",
          approvalReason: next.approvalReason ?? fallbackApprovalReason,
          reasoning: {
            what: reasoningWhat,
            why: reasoningWhy,
            context: {
              zh: `觸發規則：${next.reason.zh}`,
              en: `Triggered rule: ${next.reason.en}`,
            },
          },
          riskProfile: buildSimulatedRiskProfile(
            next.agent,
            next.amount,
            next.merchant,
            next.reason,
          ),
        });

        const agentName = t(`agent.${next.agent}.name`);
        const title = t("feed.toast.pending.title", { agent: agentName });
        const desc = t("feed.toast.pending.desc", {
          merchant: next.merchant[locale],
          amount: next.amount.toFixed(2),
          reason: next.reason[locale],
        });
        toast.warning(title, { description: desc });
        notify(title, desc);
      }
    };
    // 12s instead of 3s — long enough that the activity feel stays alive
    // without burying the canvas under toast notifications during a demo.
    tickRef.current = setInterval(tick, 12000);
    return () => {
      if (tickRef.current) clearInterval(tickRef.current);
    };
  }, [limit, locale, t, notify]);

  // DemoControls hooks — resolve-pending mimics a user click on the first
  // pending row's amber pill (any merchant); reset restores the initial mock
  // items.
  useEffect(() => {
    const onResolvePending = () => {
      const next = items.find(
        (i) => i.status === "pending" && !resolving.has(i.id),
      );
      if (next) handleResolve(next.id);
    };
    const onReset = () => {
      setItems(liveFeed.slice(0, limit));
      setResolving(new Set());
    };
    window.addEventListener(DEMO_EVENTS.resolvePending, onResolvePending);
    window.addEventListener(DEMO_EVENTS.reset, onReset);
    return () => {
      window.removeEventListener(DEMO_EVENTS.resolvePending, onResolvePending);
      window.removeEventListener(DEMO_EVENTS.reset, onReset);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [items, resolving, limit]);

  const filtered = useMemo(() => {
    if (filter === "all") return items;
    if (filter === "pending") return items.filter((i) => i.status === "pending");
    if (filter === "auto") return items.filter((i) => i.status === "auto-approved");
    // "recent" — pass-through for the mock; all items are timestamped within
    // the past hour by construction. Becomes a real filter once timestamps
    // carry absolute dates.
    return items;
  }, [items, filter]);

  return (
    <div>
      {/* Header: title with blue tick mark + "即時" live pill + view-all link */}
      <div className="flex items-center justify-between gap-3 pb-4 flex-wrap">
        <div className="flex items-center gap-3">
          <h2
            className="flex items-center gap-2.5 text-[13px] font-semibold"
            style={{
              color: "var(--headline)",
              fontFamily: "var(--font-noto-sans-tc), sans-serif",
            }}
          >
            <span
              aria-hidden
              className="h-px w-[14px]"
              style={{ background: "var(--ikea-blue)" }}
            />
            {t("feed.title")}
          </h2>
          <span
            className="inline-flex items-center gap-1.5 px-2.5 py-0.5 text-[11px] font-medium"
            style={{
              color: "var(--ikea-blue-darker)",
              background: "var(--bg-accent)",
              border: "1px solid var(--ikea-blue)",
            }}
          >
            <span className="relative flex h-1.5 w-1.5">
              <span
                className="absolute inline-flex h-full w-full animate-ping rounded-full opacity-60"
                style={{ background: "var(--ikea-blue)" }}
              />
              <span
                className="relative inline-flex h-1.5 w-1.5 rounded-full"
                style={{
                  background: "var(--ikea-blue)",
                  boxShadow: "0 0 8px var(--ikea-blue)",
                }}
              />
            </span>
            {t("feed.live")}
          </span>
        </div>
        {viewAllHref && (
          <Link
            href={viewAllHref}
            className="group inline-flex items-center gap-1 text-[12px] transition-colors"
            style={{ color: "var(--text-mid)" }}
          >
            {t("feed.viewAll")}
            <span className="transition-transform group-hover:translate-x-0.5">→</span>
          </Link>
        )}
      </div>

      {/* Filter pills */}
      <div className="flex items-center gap-1.5 mb-3 flex-wrap">
        {FILTERS.map((f) => (
          <button
            key={f}
            type="button"
            onClick={() => setFilter(f)}
            aria-pressed={filter === f}
            className={cn("feed-filter-pill", filter === f && "is-active")}
          >
            {t(`feed.filter.${f}`)}
          </button>
        ))}
      </div>

      {/* List + footer — single bordered box with the list above and the
          view-all button below. */}
      <div
        style={{
          background: "var(--card)",
          border: "1px solid var(--border)",
        }}
      >
        <ul>
          {filtered.length === 0 && (
            <li
              className="p-6 text-center text-[12px]"
              style={{ color: "var(--text-mid)" }}
            >
              —
            </li>
          )}
          {filtered.map((item, i) => {
            const isPending = item.status === "pending";
            const isResolving = resolving.has(item.id);
            const tone = ruleTone(item.reason[locale]);
            const relative = item.relative?.[locale] ?? t("feed.relative.justNow");
            const isLast = i === filtered.length - 1;

            const row = (
              <li
                key={item.id}
                className={cn(
                  "activity-row",
                  isPending && "is-pending",
                  isResolving && "resolving",
                )}
                style={isLast ? { borderBottom: "none" } : undefined}
              >
                {/* Agent icon — 36x36 square tile with same-hue outer ring */}
                <AgentIcon agent={item.agent} size="md" outlined />

                {/* Main info: agent name → merchant, then time + relative */}
                <div className="min-w-0 flex flex-col gap-0.5">
                  <div className="flex items-center gap-1.5 flex-wrap text-[13px]">
                    <span
                      className="font-mono"
                      style={{ color: "var(--text-mid)" }}
                    >
                      {t(`agent.${item.agent}.name`)}
                    </span>
                    <span
                      aria-hidden
                      style={{ color: "var(--ikea-blue)" }}
                    >
                      ▸
                    </span>
                    <span
                      className="truncate"
                      style={{ color: "var(--headline)" }}
                    >
                      {item.merchant[locale]}
                    </span>
                  </div>
                  <div
                    className="flex flex-wrap items-center gap-1.5 text-[11px] font-mono tabular-nums"
                    style={{ color: "var(--text-dim)" }}
                  >
                    <span>{item.time} · {relative}</span>
                    <span aria-hidden>·</span>
                    <span>{getAgentPlatformLabel(item.agent, locale)}</span>
                  </div>
                  {isPending && item.approvalReason && (
                    <div
                      className="text-[11px] leading-relaxed"
                      style={{ color: "var(--text-mid)" }}
                    >
                      {t("approval.reason.label")}:{" "}
                      {item.approvalReason[locale]}
                    </div>
                  )}
                </div>

                {/* Rule pill */}
                <span
                  className={cn(
                    "rule-pill",
                    tone === "warn" ? "rule-pill-warn" : "rule-pill-ok",
                  )}
                >
                  <span className="rule-pill-dot" />
                  <span className="truncate">{item.reason[locale]}</span>
                </span>

                {/* Amount — mono, deep-blue digits + small gray USDC */}
                <span
                  className="activity-amount text-[13px] font-mono font-semibold tabular-nums text-right whitespace-nowrap"
                  style={{ color: "var(--headline)" }}
                >
                  {item.amount.toFixed(2)}
                  <span
                    className="ml-1 text-[10px] font-normal"
                    style={{ color: "var(--text-dim)" }}
                  >
                    USDC
                  </span>
                </span>

                {/* Status — auto (gray + sage dot) or pending (amber pill).
                    Clicking the pending pill resolves the row in place
                    (sage wash → slide out 600ms) and bumps the dashboard
                    count. stopPropagation prevents the outer Link from also
                    navigating to /approvals. */}
                {isPending ? (
                  <button
                    type="button"
                    className="status-pending"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      handleResolve(item.id);
                    }}
                  >
                    <span className="status-pending-dot" />
                    {t("feed.status.pending")}
                  </button>
                ) : (
                  <span className="status-auto">
                    <span className="status-auto-dot" />
                    {t("feed.status.autoApproved")}
                  </span>
                )}
              </li>
            );

            // Pending rows are clickable — route to /approvals.
            return isPending ? (
              <Link key={item.id} href="/approvals" className="block">
                {row}
              </Link>
            ) : (
              row
            );
          })}
        </ul>

        {/* Footer: full-width link to the audit page. Merges into the outer
            list box and points at the same destination as the header link. */}
        <Link href={viewAllHref} className="feed-view-all">
          {t("feed.viewAllTransactions", { n: stats.todayTransactions })}
        </Link>
      </div>
    </div>
  );
}
